name: test
on:
  # Open a PR to update README for all PRs (as necessary)
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  terraform:
    runs-on: ubuntu-latest
    container: cloudposse/testing.cloudposse.co:pr-91-merge
    env: 
      PATH: "/usr/local/terraform/0.12/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      BUILD_HARNESS_BRANCH: master
      TEST_HARNESS_BRANCH: master
      MAKE_INCLUDES: Makefile
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v1
    - name: "Initialize build-harness"
      run: make init
    - name: "Initialize test-harness"
      run: make -C test/ clean init
    - name: "Initialize terragrunt tests"
      run: make -C test/src clean init
    - name: "Test README.md updated"
      run: make readme/lint
    - name: "Test module with bats"
      run: make -C test/ module
    - name: "Test `examples/complete` with bats"
      run: make -C test/ examples/complete
    - name: "Test `examples/complete` with terratest"
      run: make -C test/src
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
