name: test
on:
  # Open a PR to update README for all PRs (as necessary)
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    container: cloudposse/testing.cloudposse.co:pr-91-merge
    steps:
    - name: Run in container
      run: |
        echo This job does specify a container.
        echo It runs in the container instead of the VM.
