name: test
on:
  # Open a PR to update README for all PRs (as necessary)
  pull_request: 
    types: [opened, synchronize, reopened]

jobs:
  docker/login:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/cloudposse/testing.cloudposse.co/default:sha-2c86b39
    steps:
    - name: Run in container
      run: |
        echo This job does specify a container.
        echo It runs in the container instead of the VM.
